version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env

  job-tracker-app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - .env
