# Generated by Django 5.1.4 on 2024-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=24)),
                ('company_name', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=24)),
                ('commute_time', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='NEW', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('vacation_days', models.IntegerField()),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
            ],
        ),
    ]
