# Generated by Django 5.1.4 on 2025-01-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commute_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacation_days',
            field=models.PositiveIntegerField(),
        ),
    ]
