# Generated by Django 5.1.4 on 2025-02-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_address_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact'),
        ),
    ]
