# Generated by Django 5.2.1 on 2025-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_job_company_name_alter_job_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
